SQL_SERVER="[2601:19b:200:5d80:1582:1e97:69e1:21a9],1433"
SQL_DATABASE="big_data_assignment1"
SQL_USER="sa"
SQL_PASSWORD="881007"

AWS_BUCKET="demo-damg7245-fall2024"
AWS_ACCESS_KEY_ID="AKIAZ3MGMZIEXX4ES7HQ"
AWS_SECRET_ACCESS_KEY="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"


OPENAI_API_KEY="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"

HuggingFace_API_KEY="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"