[sql_server]
address = "[2601:19b:200:5d80:1582:1e97:69e1:21a9],1433"
database = "big_data_assignment1"
user = "sa"
password = "881007"

[aws]
bucket = "demo-damg7245-fall2024"
access_key_id = "AKIAZ3MGMZIEXX4ES7HQ"
secret_access_key = "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"

[openai]
api_key = "sk-svcacct-JzP7Z0eqo3chvJx39lApSVh8i7C6gruhpSuz6USVlzp9h-s27P4iEX-IaEOGq23wMaaAUT3BlbkFJaagN5r70jgikCl9DAjnGtUqTOK-eUSbV1Eu2-zWW-W3nQGtmHoCYQcfcJPdWivQG8GsAA"

[huggingface]
api_key = "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"
